[tool.poetry]
name = "ForecastGA"
version = "0.1.14"
description = "A Python tool to forecast GA data using several popular timeseries models"
authors = ["JR Oakes <jroakes@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/jroakes/ForecastGA"
repository = "https://github.com/jroakes/ForecastGA"
keywords = ["google analytics", "forecasting", "python"]
packages = [
    { include = "forecastga", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.6.2"
pylev = "^1.3.0"
addressable = "^1.4.2"
colorama = "^0.4.4"
fbprophet = "^0.7.1"
gluonts = "^0.6.4"
google-api-core = "^1.24.1"
google-api-python-client = "^1.12.8"
google-auth-httplib2 = "^0.0.4"
google-auth = "^1.24.0"
holidays = "^0.10.4"
httplib2 = "^0.18.1"
inspect-it = "^0.3.2"
keyring = "^21.8.0"
lightgbm = "^3.1.1"
matplotlib = "3.2.2"
oauth2client = "^4.1.3"
pmdarima = "^1.8.0"
prettytable = "^2.0.0"
pystan = "^2.19.1"
python-dateutil = "^2.8.1"
PyYAML = "^5.3.1"
requests = "^2.25.1"
rsa = "^4.6"
scikit-learn = "^0.24.0"
scipy = "1.5.0"
seasonal = "^0.3.1"
snakify = "^1.1.1"
statsmodels = "^0.12.1"
tbats = "^1.1.0"
torch = "^1.7.1"
tqdm = "^4.55.1"
Werkzeug = "^1.0.1"
mxnet = "^1.7.0"
tsfresh = "^0.17.0"
MarkupSafe = "^1.1.1"
setuptools = "^51.1.1"
pandas = "1.0.5"
numpy = "1.19.3"
nbeats-pytorch = "^1.3.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
prospector = {extras = ["with_pyroma"], version = "^1.3.1"}
bumpversion = "^0.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
