[tool.poetry]
name = "dj-qiyu-tpl"
version = "0.2.0"
description = "Template for internal use"
authors = ["dev <dev@qiyutech.tech>"]
readme = "README.md"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple"
default = true

[tool.poetry.dependencies]
python = "^3.9"

django = ">=3.1,<3.2"

[tool.poetry.dev-dependencies]
black = ">=20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
