[tool.poetry]
name = "pytest-drivings"
version = "1.0"
description = "Tool to allow webdriver automation to be ran locally or remotely"
authors = ["Jonah Caruso <jayc035@yahoo.com>"]

[[tool.poetry.source]]
name = "public"
url = 'https://pypi.python.org/simple'

[tool.poetry.plugins."pytest11"]
"pytest_webdriver" = "pytest_webdriver.webdriver"

[tool.poetry.dependencies]
python = ">=3.7"
paramiko = "^2.7.1"
selenium = "^3.141.0"
selenium-requests = "^1.3"
psutil = "^5.6.7"
pytest-xdist = "^1.31.0"
black = {version = "^19.3b0", allow-prereleases = true}
mypy = "^0.720"
deprecation = "^2.0.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
