[tool.poetry]
name = "databricks-bundle"
version = "0.6.0a12"
description = "Databricks bundle for the Pyfony framework"
readme = "README.md"
repository = "https://github.com/bricksflow/databricks-bundle"

license = "MIT"

authors = [
    "Jiri Koutny <jiri.koutny@datasentics.com>"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

include = ["*.yaml"]

packages = [
    { include = "databricksbundle", from = "src" },
]

[tool.poetry.dependencies]
python = "~3.7.3"
pyfony-bundles = ">=0.2.5a2"
injecta = ">=0.8.13b1"
logger-bundle = ">=0.6.0a3"
console-bundle = ">=0.3.0a5"

[tool.poetry.dev-dependencies]
databricks-connect = "^7.3"
pylint = "2.4.*"
pytest = "5.2.*"
bricksflow-core = ">=0.6.0a13"

[tool.poetry.plugins."pyfony.bundle"]
autodetect = "databricksbundle.DatabricksBundle:DatabricksBundle.autodetect"

[tool.poetry.plugins."pyfony.testing_scope"]
console = "databricksbundle.DatabricksBundle:DatabricksBundle.createForConsoleTesting"
notebook = "databricksbundle.DatabricksBundle:DatabricksBundle.createForNotebookTesting"

[pyfony.bootstrap]
containerInit = "databricksbundle.containerInit:initContainer"
