[tool.poetry]
name = "pyfony-core"
version = "0.7.0a6"
description = "Pyfony core"
readme = "README.md"
repository = "https://github.com/pyfony/core"

license = "MIT"

authors = [
    "Jiri Koutny <jiri.koutny@datasentics.com>"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

include = ["*.yaml"]

packages = [
    { include = "pyfonycore", from = "src" },
]

[tool.poetry.dependencies]
python = "~3.7.3"
injecta = "^0.8.11"
pyfony-bundles = "0.2.5a2"

[tool.poetry.dev-dependencies]
pylint = "2.4.*"
pytest = "5.2.*"
