[tool.poetry]
name = "si_utils"
version = "0.1.5"
description = "an opinionated set of utilities designed to be easily included in any number of projects"
authors = ["Alex Tremblay <alex.tremblay@utoronto.ca>", "University of Toronto"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.6,<4.0"
loguru = {version = "^0.5", optional = true}
sentry-sdk = {version = "^0.19", optional = true}
"ruamel.yaml" = {version = "^0.16", optional = true}
deepmerge = {version = "^0.1", optional = true}
pydantic = {version = "^1", optional = true}
tomlkit = {version = "^0.7.0", optional = true}
semver = {version = "^2.13.0", optional = true}

[tool.poetry.extras]
log = ["loguru", "sentry-sdk"]
yaml = ["ruamel.yaml", "deepmerge", "pydantic"]
dev-utils = ["tomlkit", "semver"]

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.6.0"
mypy = "^0.790"
flake8 = "^3.8.4"
poethepoet = "^0.9.0"

[tool.poe.tasks]
bump-version = {script = "si_utils.dev_utils:bump_version"}
upgrade-vendored-deps = {shell = """\
    cd si_utils/_vendor; \
    pip install -U -t . appdirs boltons decorator; \
    """}
sudo-install = {shell = """\
    rm -f dist/*; \
	poetry build; \
	sudo /usr/local/bin/pip3 install dist/*.whl; \
    """}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
